name: mongo_aplication
description: A new Flutter project.

environment:
  sdk: ">=2.17.0 <3.0.0"
  # Asegúrate de que esto sea >=2.12.0

dependencies:
  flutter:
    sdk: flutter
  material_color_utilities: ^0.11.1  # Cambiado a la versión que requiere Flutter SDK
  async: ^2.13.0
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  vm_service: ^15.0.0
  mongo_dart: ^0.8.0 # o la última versión disponible
dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true



